name: BurgerQ CD

on:
  push:
    branches:
      - main

env:
  SERVER_NAME: burgerq-server

jobs:
  Build-Push-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVER_NAME }}:latest
          build-args: |
            PROFILE=prod
            DB_URL_PROD=${{ secrets.DB_URL_PROD }}
            DB_USERNAME_PROD=${{ secrets.DB_USERNAME_PROD }}
            DB_PASSWORD_PROD=${{ secrets.DB_PASSWORD_PROD }}

      - name: Docker Deploy executing remote ssh commands using ssh_key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            docker stop ${{ env.SERVER_NAME }} || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVER_NAME }}
            docker rm -f ${{ env.SERVER_NAME }} || true
            docker run -d --name ${{ env.SERVER_NAME }} -p ${{ secrets.SERVER_PORT }}:8080 ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVER_NAME }}
            docker image prune -f